apiVersion: aws.managed.openshift.io/v1alpha1
kind: AWSFederatedRole
metadata:
  name: read-only
  namespace: aws-account-operator
  annotations:
    package-operator.run/phase: deploy
spec:
  roleDisplayName: Read only
  roleDescription: User may view all AWS resources for this cluster, but not modify, create or delete resources.
  awsCustomPolicy:
    name:  BillingReadOnlyAccess
    description: Description of BillingReadOnlyAccess
    awsStatements:
      - effect: Allow
        action:
          - "aws-portal:ViewAccount"
          - "aws-portal:ViewBilling"
        resource:
          - "*"
  awsManagedPolicies:
    - "AWSAccountUsageReportAccess"
    - "AmazonEC2ReadOnlyAccess"
    - "AmazonS3ReadOnlyAccess"
    - "IAMReadOnlyAccess"
    - "CloudWatchReadOnlyAccess"
