apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: aws-account-operator
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - aws.managed.openshift.io
  resources:
  - '*'
  - accountclaims
  - accounts
  - accountpools
  - awsfederatedaccountaccesses
  - awsfederatedroles
  verbs:
  - '*'
