apiVersion: v1
kind: Template
metadata:
  name: olm-artifacts-template

parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  value: staging
- name: IMAGE_TAG
  value: latest

objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: aws-account-operator-catalog
  spec:
    sourceType: grpc
    image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
    displayName: aws-account-operator Registry
    publisher: SRE 

- apiVersion: operators.coreos.com/v1alpha2
  kind: OperatorGroup
  metadata:
    name: aws-account-operator-og
  spec:
    targetNamespaces:
    - aws-account-operator

- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: aws-account-operator
  spec:
    channel: ${CHANNEL}
    name: aws-account-operator
    source: aws-account-operator-catalog
    sourceNamespace: aws-account-operator

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: aws-account-operator-client
  rules:
  - apiGroups:
    - "aws.managed.openshift.io"
    resources:
    - accountclaims
    verbs:
    - create
    - delete
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - create
    - update

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: aws-account-operator-client
  subjects:
  - kind: ServiceAccount
    namespace: aws-account-operator-client
    name: aws-account-operator-client
  - kind: Group
    name: aws-account-operator-client
  roleRef:
    kind: ClusterRole
    name: aws-account-operator-client
    apiGroup: rbac.authorization.k8s.io