apiVersion: v1
kind: Template
parameters:
  - name: CHANNEL
    required: false
  - name: OPERATOR_IMAGE
    required: true
  - name: PKO_IMAGE
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE_DIGEST
    required: true
  - name: NAMESPACE
    value: openshift-aws-account-operator
  - name: REPO_NAME
    value: aws-account-operator
    required: true
  - name: ACCOUNT_LIMIT
    required: true
  - name: ROOT_OU_ID
    required: true
  - name: BASE_OU_ID
    required: true
  - name: STS_JUMP_ROLE
    required: true
  - name: SUPPORT_JUMP_ROLE
    required: true
  - name: SHARD_NAME
    required: true
  - name: ACCOUNT_POOL_CONFIG
    required: true
  - name: AWS_MANAGED_TAGS
    required: false
  - name: FEDRAMP
    required: false
  - name: DEBUG_LOGGING
    required: false
metadata:
  name: clusterpackage-template
objects:
  - apiVersion: package-operator.run/v1alpha1
    kind: ClusterPackage
    metadata:
      name: "${REPO_NAME}"
      annotations:
        package-operator.run/collision-protection: IfNoController
    spec:
      image: ${PKO_IMAGE}:${IMAGE_TAG}
      config:
        image: ${OPERATOR_IMAGE}:${IMAGE_TAG}
        accountLimit: ${ACCOUNT_LIMIT}
        rootOuId: ${ROOT_OU_ID}
        baseOuId: ${BASE_OU_ID}
        stsJumpRole: ${STS_JUMP_ROLE}
        supportJumpRole: ${SUPPORT_JUMP_ROLE}
        shardName: ${SHARD_NAME}
        accountPoolConfig: ${ACCOUNT_POOL_CONFIG}
        awsManagedTags: ${AWS_MANAGED_TAGS}
        fedramp: ${FEDRAMP}
        debugLogging: ${DEBUG_LOGGING}
