apiVersion: aws.managed.openshift.io/v1alpha1
kind: AWSFederatedRole
metadata:
  name: read-only
  namespace: aws-account-operator
spec:
  roleDisplayName: Read only
  roleDescription: User may view all AWS resources for this cluster, but not modify, create or delete resources.
  # Custom Policy definition
  awsCustomPolicy:
    name:  BillingReadOnlyAccess
    description: Description of BillingReadOnlyAccess
    # list of statements for the policy
    awsStatements:
      - effect: Allow
        action:
        - "aws-portal:ViewAccount"
        - "aws-portal:ViewBilling"
        resource: 
        - "*"
  # list of  AWS managed
  awsManagedPolicies:
   - "AWSAccountUsageReportAccess"
   - "AmazonEC2ReadOnlyAccess"
   - "AmazonS3ReadOnlyAccess"
   - "IAMReadOnlyAccess"
