apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: accounts.aws.managed.openshift.io
spec:
  additionalPrinterColumns:
    - JSONPath: .status.state
      description: Status the account
      name: State
      type: string
    - JSONPath: .status.claimed
      description: True if the account has been claimed
      name: Claimed
      type: boolean
    - JSONPath: .spec.claimLink
      description: Link to the account claim CR
      name: Claim
      type: string
    - JSONPath: .metadata.creationTimestamp
      description: Age since the account was created
      name: Age
      type: date
  group: aws.managed.openshift.io
  names:
    kind: Account
    listKind: AccountList
    plural: accounts
    singular: account
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Account is the Schema for the accounts API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AccountSpec defines the desired state of Account
          properties:
            awsAccountID:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            byoc:
              type: boolean
            claimLink:
              type: string
            claimLinkNamespace:
              type: string
            iamUserSecret:
              type: string
            legalEntity:
              description: LegalEntity contains Red Hat specific identifiers to the original creator the clusters
              properties:
                id:
                  type: string
                name:
                  type: string
              required:
                - id
                - name
              type: object
          required:
            - awsAccountID
            - iamUserSecret
          type: object
        status:
          description: AccountStatus defines the observed state of Account
          properties:
            claimed:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: boolean
            conditions:
              items:
                description: AccountCondition contains details for the current condition of a AWS account
                properties:
                  lastProbeTime:
                    description: LastProbeTime is the last time we probed the condition.
                    format: date-time
                    type: string
                  lastTransitionTime:
                    description: LastTransitionTime is the laste time the condition transitioned from one status to another.
                    format: date-time
                    type: string
                  message:
                    description: Message is a human-readable message indicating details about last transition.
                    type: string
                  reason:
                    description: Reason is a unique, one-word, CamelCase reason for the condition's last transition.
                    type: string
                  status:
                    description: Status is the status of the condition
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                type: object
              type: array
            reused:
              type: boolean
            rotateConsoleCredentials:
              type: boolean
            rotateCredentials:
              type: boolean
            state:
              type: string
            supportCaseID:
              type: string
          type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
