apiVersion: aws.managed.openshift.io/v1alpha1
kind: AccountClaim
metadata:
  name: corp3-org-accountclaim
spec:
  legalEntity:
    name: corp3-org
    id: 333333
  awsCredentialSecret:
    name: iam-credentials-corp3
    namespace: corp3-org-ns
  aws:
    regions:
    - name: us-east-1
  # Blank by default, the claim controller will populate this
  accountLink: ""