apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/aws-account-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.openshift.io/build-nudges: "aws-account-operator-catalog"
    pipelinesascode.tekton.dev/cancel-in-progress: 'false'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: aws-account-operator
    appstudio.openshift.io/component: aws-account-operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: aws-account-operator-bundle-on-push
  namespace: aws-account-operator-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/aws-account-operator-tenant/openshift/aws-account-operator-bundle:{{revision}}
  - name: dockerfile
    value: boilerplate/openshift/golang-osd-operator/Containerfile.bundle
  - name: path-context
    value: .
  - name: operator-image
    value: quay.io/redhat-user-workloads/aws-account-operator-tenant/openshift/aws-account-operator:latest
  - name: build-args
    value:
    - OPERATOR_NAME=aws-account-operator
  taskRunTemplate:
    serviceAccountName: build-pipeline-aws-account-operator-bundle
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/openshift/boilerplate
    - name: revision
      value: master
    - name: pathInRepo
      value: pipelines/bundle-builder/pipeline.yaml
status: {}
